//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsoleApp.MyServiceClientNamespace_Console {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceClientNamespace_Console.IMyServiceDll")]
    public interface IMyServiceDll {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyServiceDll/MessageBack", ReplyAction="http://tempuri.org/IMyServiceDll/MessageBackResponse")]
        string MessageBack(string fromClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyServiceDll/RemoteCalc", ReplyAction="http://tempuri.org/IMyServiceDll/RemoteCalcResponse")]
        double RemoteCalc(double n);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceDllChannel : ClientConsoleApp.MyServiceClientNamespace_Console.IMyServiceDll, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceDllClient : System.ServiceModel.ClientBase<ClientConsoleApp.MyServiceClientNamespace_Console.IMyServiceDll>, ClientConsoleApp.MyServiceClientNamespace_Console.IMyServiceDll {
        
        public MyServiceDllClient() {
        }
        
        public MyServiceDllClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceDllClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceDllClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceDllClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MessageBack(string fromClient) {
            return base.Channel.MessageBack(fromClient);
        }
        
        public double RemoteCalc(double n) {
            return base.Channel.RemoteCalc(n);
        }
    }
}
